project:
  type: website
  resources:
    - "*.xlsx"
    - "*.xlsm"
    - "*.xls"
    - "*.pptx"

website:
  margin-footer: |
    ![](./CHEMlogo_white.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - href: https://www.vumc.org/center-for-health-economic-modeling/
        text: Center Website (VUMC)
      - href: index.qmd
        text: Center Blog
      - href: https://graveja0.github.io/health-care-markets/
        text: Defining Markets for Health Care Services (Github)
 
filters:
   - lightbox
   
execute:
  freeze: true  # re-render only when source changes

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

