project:
  type: website
  resources:
    - "*.xlsx"
    - "*.xlsm"
    - "*.xls"
    - "*.pptx"

website:
  title: "Vanderbilt Center for Health Economic Modeling"
  margin-footer: |
    ![](./CHEMlogo_white.png)
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - index.qmd
 
filters:
   - lightbox
   
execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

